version: '3.4'

services:
  chavah.web:
    image: ${DOCKER_REGISTRY}chavah.web
    build:
      context: .
      dockerfile: Chavah.NetCore/Dockerfile
    depends_on:
      - chavah.db
  chavah.db:
    image: kdcllc/chavahdb
    ports:
      - "8181:8080"
