var BitShuva;
(function (BitShuva) {
    var Chavah;
    (function (Chavah) {
        var ConfirmEmailController = (function () {
            function ConfirmEmailController(accountApi, $routeParams) {
                var _this = this;
                this.accountApi = accountApi;
                this.email = "";
                this.confirmCode = "";
                this.isConfirming = true;
                this.confirmSucceeded = false;
                this.confirmFailed = false;
                this.confirmFailedErrorMessage = "";
                this.email = $routeParams["email"];
                // The confirm code is generated by WebAPI. We manually replace any forward slashes with triple underscore,
                // otherwise the Angular route gets busted, even with encodeURIComponent.
                var escapedConfirmCode = $routeParams["confirmCode"] || "";
                this.confirmCode = escapedConfirmCode.replace(new RegExp("___", "g"), "/"); // Put the forward slash(s) back in.
                setTimeout(function () { return _this.confirm(); }, 1000);
            }
            ConfirmEmailController.prototype.confirm = function () {
                var _this = this;
                this.accountApi.confirmEmail(this.email, this.confirmCode)
                    .then(function (results) { return _this.confirmEmailCompleted(results); })
                    .catch(function (results) { return _this.confirmEmailCompleted({
                    errorMessage: results && results.data && results.data.exceptionMessage ? results.data.exceptionMessage : "Couldn't confirm email",
                    success: false
                }); });
            };
            ConfirmEmailController.prototype.confirmEmailCompleted = function (results) {
                this.isConfirming = false;
                this.confirmSucceeded = results.success;
                this.confirmFailed = !this.confirmSucceeded;
                this.confirmFailedErrorMessage = results.errorMessage;
            };
            return ConfirmEmailController;
        }());
        ConfirmEmailController.$inject = [
            "accountApi",
            "$routeParams"
        ];
        Chavah.ConfirmEmailController = ConfirmEmailController;
        Chavah.App.controller("ConfirmEmailController", ConfirmEmailController);
    })(Chavah = BitShuva.Chavah || (BitShuva.Chavah = {}));
})(BitShuva || (BitShuva = {}));
